# Generated by Django 5.1.6 on 2025-02-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0003_education_happyclients_service_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=202)),
                ('last_name', models.CharField(max_length=202)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
